#!/usr/bin/env bash
# Bash script that displays info about subdomains

domain_information() {
    local subdomain_info
    subdomain_info=$(dig "$2"."$1" +short)

    if [[ -z "$subdomain_info" ]]; then
        echo "No information found for subdomain $2"
    else
        local record_type
        record_type=$(echo "$subdomain_info" | awk '{print $1}')
        
        # Extract the IP address or hostname for the "points to" information
        destination=$(dig "$2"."$1" +short)
        
        echo "The subdomain $2.$1 is a $record_type record and points to $destination"
    fi
}

if [ "$#" == 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
